# Google Cloud Datastoreをローカルで実行します
#
# docker-compose up -f docker-compose.db.yaml -d を使用してコンテナを実行してください

version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: cateiru-sso
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/.data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
  gcs:
    image: fsouza/fake-gcs-server
    tty: true
    stdin_open: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 4443:4443
    volumes:
      - ./.data:/data/cateiru-sso:cached
      - ./.data:/data/test-cateiru-sso:cached
      - ./.storage:/storage
    command: -scheme http -public-host ${STORAGE_URL:-localhost:4443}
