'use client';

import {Button} from '@chakra-ui/react';
import {Card} from '../Common/Card';
import {Link} from '../Common/Next/Link';

export const Staff = () => {
  return (
    <>
      <Card
        title="ユーザー"
        description="現在登録されているアカウント一覧です。"
      >
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/users"
        >
          ユーザー一覧
        </Button>
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          mt="1rem"
          href="/staff/user_names"
        >
          予約されているユーザー名の一覧
        </Button>
      </Card>
      <Card
        title="ブランド"
        description="ユーザーに特別な権限を与えることができるブランドの設定です。"
      >
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/brands"
        >
          ブランド一覧
        </Button>
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/brand/register"
          mt="1rem"
        >
          ブランド新規作成
        </Button>
      </Card>
      <Card
        title="クライアント"
        description="ユーザーが作成したクライアントの一覧です。"
      >
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/clients"
        >
          クライアント一覧
        </Button>
      </Card>
      <Card
        title="組織"
        description="ユーザーをグループ化して個別に機能を提供する組織の設定です。"
      >
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/orgs"
        >
          組織一覧
        </Button>
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/org/register"
          mt="1rem"
        >
          組織新規作成
        </Button>
      </Card>
      <Card title="セッション">
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/register_session"
        >
          登録セッション
        </Button>
      </Card>
      <Card title="その他">
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          href="/staff/deploy_data"
        >
          デプロイデータ
        </Button>
        <Button
          variant="outline"
          colorScheme="cateiru"
          w="100%"
          as={Link}
          mt="1rem"
          href="/staff/email_template_preview"
        >
          メールテンプレートプレビュー
        </Button>
      </Card>
    </>
  );
};
