# Google Cloud Datastoreをローカルで実行します
#
# docker compose -f ./docker/docker-compose.db.yaml up を使用してコンテナを実行してください
services:
  db:
    build:
      context: ..
      dockerfile_inline: |
        FROM mysql:8.0-debian

        RUN apt update && apt install -y curl

        # Install https://github.com/golang-migrate/migrate
        RUN curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | bash \
          && apt install -y migrate

    container_name: db
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: local
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../db/.data:/var/lib/mysql
      - ../db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../db/setup:/docker-entrypoint-initdb.d
      - ../db/migrations:/migrations
    ports:
      - "127.0.0.1:3306:3306"
  gcs:
    image: fsouza/fake-gcs-server
    tty: true
    stdin_open: true
    privileged: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 4443:4443
    volumes:
      - ../.data:/data/oreore-me:cached
      - ../.data:/data/test-oreore-me:cached
      - ../.storage:/storage
    command: -scheme http -public-host localhost:4443
