'use client';

import {Box, keyframes, usePrefersReducedMotion} from '@chakra-ui/react';
import React from 'react';

// /***************************************************
//  * Generated by SVG Artista on 5/18/2023, 8:31:33 PM
//  * MIT license (https://opensource.org/licenses/MIT)
//  * W. https://svgartista.net
//  **************************************************/

const animateSvgStroke1 = keyframes`
  0% {
    stroke-dashoffset: 2810.565673828125px;
    stroke-dasharray: 2810.565673828125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 2810.565673828125px;
  }
`;

const animateSvgStroke2 = keyframes`
  0% {
    stroke-dashoffset: 1404.71923828125px;
    stroke-dasharray: 1404.71923828125px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1404.71923828125px;
  }
`;

const animateSvgStroke3 = keyframes`
  0% {
    stroke-dashoffset: 1404.7193603515625px;
    stroke-dasharray: 1404.7193603515625px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1404.7193603515625px;
  }
`;

const animateSvgStroke4 = keyframes`
  0% {
    stroke-dashoffset: 1056.8255615234375px;
    stroke-dasharray: 1056.8255615234375px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 1056.8255615234375px;
  }
`;

const animateSvgStroke5 = keyframes`
  0% {
    stroke-dashoffset: 134.4873809814453px;
    stroke-dasharray: 134.4873809814453px;
  }

  100% {
    stroke-dashoffset: 0;
    stroke-dasharray: 134.4873809814453px;
  }
`;

export const Logo: React.FC<{size: string}> = ({size = '300px'}) => {
  const prefersReducedMotion = usePrefersReducedMotion();

  return (
    <Box
      as="svg"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 512 512"
      width={size}
      height={size}
    >
      <defs>
        <linearGradient id="a">
          <stop offset="0" stopColor="#57d3db"></stop>
          <stop offset=".5" stopColor="#7957db"></stop>
          <stop offset="1" stopColor="#dc56b6"></stop>
        </linearGradient>
        <linearGradient
          xlinkHref="#a"
          id="b"
          x1="85.7"
          x2="398.9"
          y1="340.2"
          y2="340.2"
          gradientTransform="translate(-77 -200) scale(1.29832)"
          gradientUnits="userSpaceOnUse"
        ></linearGradient>
      </defs>
      <Box
        as="path"
        fill="none"
        stroke="#1f1f1f"
        strokeDashoffset="1"
        strokeOpacity=".9"
        strokeWidth="50"
        d="M68 80h340c18 0 33 15 33 34v256c0 19-15 34-33 34H68c-19 0-34-15-34-34V114c0-19 15-34 34-34zm36 28h340c19 0 34 15 34 34v256c0 19-15 34-34 34H104c-18 0-33-15-33-34V142c0-19 15-34 33-34z"
        animation={
          prefersReducedMotion
            ? undefined
            : `${animateSvgStroke1} 1s cubic-bezier(0.55, 0.055, 0.675, 0.19) 0s both`
        }
      ></Box>
      <Box
        as="rect"
        width="406.6px"
        height="323.6px"
        x="71"
        y="108"
        fill="#e8e8e8"
        ry="33.4"
        animation={
          prefersReducedMotion
            ? undefined
            : `${animateSvgStroke2} 1s cubic-bezier(0.55, 0.055, 0.675, 0.19) 0.12s both`
        }
      ></Box>
      <Box
        as="rect"
        width="406.6px"
        height="323.6px"
        x="34"
        y="80"
        fill="url(#b)"
        ry="33.4"
        animation={
          prefersReducedMotion
            ? undefined
            : `${animateSvgStroke3} 1s cubic-bezier(0.55, 0.055, 0.675, 0.19) 0.24s both`
        }
      ></Box>
      <Box
        as="path"
        fill="#e8e8e8"
        d="M218 218h37l57 206H163Zm90 16a70 70 0 0 1-70 70 70 70 0 0 1-71-70 70 70 0 0 1 71-70 70 70 0 0 1 70 70z"
        animation={
          prefersReducedMotion
            ? undefined
            : `${animateSvgStroke4} 1s cubic-bezier(0.55, 0.055, 0.675, 0.19) 0.36s both`
        }
      ></Box>
      <Box
        as="path"
        fill="#e8e8e8"
        stroke="#e8e8e8"
        strokeDashoffset="1"
        strokeWidth="20"
        d="m299 105-21 39m59-9-34 28m59 17-43 10"
        animation={
          prefersReducedMotion
            ? undefined
            : `${animateSvgStroke5} 1s cubic-bezier(0.55, 0.055, 0.675, 0.19) 0.48s both`
        }
      ></Box>
    </Box>
  );
};
