// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Brand                         string
	BroadcastEntry                string
	BroadcastNotice               string
	CertificateSession            string
	Client                        string
	ClientAllowRule               string
	ClientQuiz                    string
	ClientRefresh                 string
	ClientScope                   string
	ClientSession                 string
	EmailVerifySession            string
	LoginClient                   string
	LoginClientHistory            string
	LoginClientScope              string
	LoginHistory                  string
	LoginTryHistory               string
	OauthSession                  string
	Otp                           string
	OtpBackup                     string
	OtpSession                    string
	Passkey                       string
	PasskeyLoginDevice            string
	Password                      string
	Refresh                       string
	RegisterOtpSession            string
	RegisterSession               string
	ReregistrationPasswordSession string
	Session                       string
	Setting                       string
	Staff                         string
	User                          string
	WebauthnSession               string
}{
	Brand:                         "brand",
	BroadcastEntry:                "broadcast_entry",
	BroadcastNotice:               "broadcast_notice",
	CertificateSession:            "certificate_session",
	Client:                        "client",
	ClientAllowRule:               "client_allow_rule",
	ClientQuiz:                    "client_quiz",
	ClientRefresh:                 "client_refresh",
	ClientScope:                   "client_scope",
	ClientSession:                 "client_session",
	EmailVerifySession:            "email_verify_session",
	LoginClient:                   "login_client",
	LoginClientHistory:            "login_client_history",
	LoginClientScope:              "login_client_scope",
	LoginHistory:                  "login_history",
	LoginTryHistory:               "login_try_history",
	OauthSession:                  "oauth_session",
	Otp:                           "otp",
	OtpBackup:                     "otp_backup",
	OtpSession:                    "otp_session",
	Passkey:                       "passkey",
	PasskeyLoginDevice:            "passkey_login_device",
	Password:                      "password",
	Refresh:                       "refresh",
	RegisterOtpSession:            "register_otp_session",
	RegisterSession:               "register_session",
	ReregistrationPasswordSession: "reregistration_password_session",
	Session:                       "session",
	Setting:                       "setting",
	Staff:                         "staff",
	User:                          "user",
	WebauthnSession:               "webauthn_session",
}
