// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testOauthSessions(t *testing.T) {
	t.Parallel()

	query := OauthSessions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testOauthSessionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOauthSessionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := OauthSessions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOauthSessionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OauthSessionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testOauthSessionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := OauthSessionExists(ctx, tx, o.Code)
	if err != nil {
		t.Errorf("Unable to check if OauthSession exists: %s", err)
	}
	if !e {
		t.Errorf("Expected OauthSessionExists to return true, but got false.")
	}
}

func testOauthSessionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	oauthSessionFound, err := FindOauthSession(ctx, tx, o.Code)
	if err != nil {
		t.Error(err)
	}

	if oauthSessionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testOauthSessionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = OauthSessions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testOauthSessionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := OauthSessions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testOauthSessionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	oauthSessionOne := &OauthSession{}
	oauthSessionTwo := &OauthSession{}
	if err = randomize.Struct(seed, oauthSessionOne, oauthSessionDBTypes, false, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}
	if err = randomize.Struct(seed, oauthSessionTwo, oauthSessionDBTypes, false, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = oauthSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = oauthSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OauthSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testOauthSessionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	oauthSessionOne := &OauthSession{}
	oauthSessionTwo := &OauthSession{}
	if err = randomize.Struct(seed, oauthSessionOne, oauthSessionDBTypes, false, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}
	if err = randomize.Struct(seed, oauthSessionTwo, oauthSessionDBTypes, false, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = oauthSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = oauthSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func oauthSessionBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func oauthSessionAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *OauthSession) error {
	*o = OauthSession{}
	return nil
}

func testOauthSessionsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &OauthSession{}
	o := &OauthSession{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OauthSession object: %s", err)
	}

	AddOauthSessionHook(boil.BeforeInsertHook, oauthSessionBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	oauthSessionBeforeInsertHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.AfterInsertHook, oauthSessionAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	oauthSessionAfterInsertHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.AfterSelectHook, oauthSessionAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	oauthSessionAfterSelectHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.BeforeUpdateHook, oauthSessionBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	oauthSessionBeforeUpdateHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.AfterUpdateHook, oauthSessionAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	oauthSessionAfterUpdateHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.BeforeDeleteHook, oauthSessionBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	oauthSessionBeforeDeleteHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.AfterDeleteHook, oauthSessionAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	oauthSessionAfterDeleteHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.BeforeUpsertHook, oauthSessionBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	oauthSessionBeforeUpsertHooks = []OauthSessionHook{}

	AddOauthSessionHook(boil.AfterUpsertHook, oauthSessionAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	oauthSessionAfterUpsertHooks = []OauthSessionHook{}
}

func testOauthSessionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOauthSessionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(oauthSessionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testOauthSessionToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local OauthSession
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, oauthSessionDBTypes, false, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := OauthSessionSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*OauthSession)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testOauthSessionToOneClientUsingClient(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local OauthSession
	var foreign Client

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, oauthSessionDBTypes, false, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, clientDBTypes, false, clientColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Client struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.ClientID = foreign.ClientID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Client().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ClientID != foreign.ClientID {
		t.Errorf("want: %v, got %v", foreign.ClientID, check.ClientID)
	}

	ranAfterSelectHook := false
	AddClientHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Client) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := OauthSessionSlice{&local}
	if err = local.L.LoadClient(ctx, tx, false, (*[]*OauthSession)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Client == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Client = nil
	if err = local.L.LoadClient(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Client == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testOauthSessionToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a OauthSession
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, oauthSessionDBTypes, false, strmangle.SetComplement(oauthSessionPrimaryKeyColumns, oauthSessionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.OauthSessions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}
func testOauthSessionToOneSetOpClientUsingClient(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a OauthSession
	var b, c Client

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, oauthSessionDBTypes, false, strmangle.SetComplement(oauthSessionPrimaryKeyColumns, oauthSessionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, clientDBTypes, false, strmangle.SetComplement(clientPrimaryKeyColumns, clientColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, clientDBTypes, false, strmangle.SetComplement(clientPrimaryKeyColumns, clientColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Client{&b, &c} {
		err = a.SetClient(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Client != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.OauthSessions[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.ClientID != x.ClientID {
			t.Error("foreign key was wrong value", a.ClientID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.ClientID))
		reflect.Indirect(reflect.ValueOf(&a.ClientID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.ClientID != x.ClientID {
			t.Error("foreign key was wrong value", a.ClientID, x.ClientID)
		}
	}
}

func testOauthSessionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOauthSessionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := OauthSessionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testOauthSessionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := OauthSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	oauthSessionDBTypes = map[string]string{`Code`: `varchar`, `UserID`: `varchar`, `ClientID`: `varchar`, `Nonce`: `varchar`, `AuthTime`: `datetime`, `Period`: `datetime`, `CreatedAt`: `datetime`, `UpdatedAt`: `datetime`}
	_                   = bytes.MinRead
)

func testOauthSessionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(oauthSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(oauthSessionAllColumns) == len(oauthSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testOauthSessionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(oauthSessionAllColumns) == len(oauthSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &OauthSession{}
	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, oauthSessionDBTypes, true, oauthSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(oauthSessionAllColumns, oauthSessionPrimaryKeyColumns) {
		fields = oauthSessionAllColumns
	} else {
		fields = strmangle.SetComplement(
			oauthSessionAllColumns,
			oauthSessionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := OauthSessionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testOauthSessionsUpsert(t *testing.T) {
	t.Parallel()

	if len(oauthSessionAllColumns) == len(oauthSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLOauthSessionUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := OauthSession{}
	if err = randomize.Struct(seed, &o, oauthSessionDBTypes, false); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OauthSession: %s", err)
	}

	count, err := OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, oauthSessionDBTypes, false, oauthSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize OauthSession struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert OauthSession: %s", err)
	}

	count, err = OauthSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
