version: "3"

services:
  api:
    build: .
    ports:
      - 3001:3001
    links:
      - datastore
    environment:
      - DEPLOY_MODE=debug
      - PORT=3001
      - ADMIN_MAIL=test@cateiru.com
      - ADMIN_PASSWORD=password
      - COOKIE_DOMAIN=192.168.3.253
      - SITE_DOMAIN=192.168.3.253:3000
      - API_DOMAIN=192.168.3.253:3001
      - CORS=http://192.168.3.253:3000
      - ISSUER=test_user
      - RECAPTCHA_SECRET=
      - MAILGUN_API_KEY=
      - MAIL_FROM_DOMAIL=
      - SENDER_MAIL_ADDRESS=
      - DATASTORE_PARENT_KEY=test-cateiru-sso
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_EMULATOR_HOST=datastore:18001
      - STORAGE_EMULATOR_HOST=gcs:4443
      - STORAGE_URL=http://192.168.3.253:4443
