name: Package test

on:
  push:
    paths:
      - 'pkg/**'
  pull_request:
    branches: [ main ]

jobs:
  go:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      working-directory: ./pkg/go
      run: go build -v ./...

    - name: Test
      working-directory: ./pkg/go
      run: go test -v ./...
