
name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nextjs:
    name: next test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        working-directory: ./front
        run: yarn install --dev
      - name: Run gts
        working-directory: ./front
        run: yarn lint
      - name: Build
        working-directory: ./front
        run: yarn build
  go:
    name: go test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      working-directory: ./api
      run: go build -v ./...

    - name: Test
      working-directory: ./api
      run: |
        docker-compose up -d
        go test ./... -v -coverpkg=./... -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage to Codecov
      working-directory: ./api
      run: bash <(curl -s https://codecov.io/bash)
    
