
name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nextjs:
    name: next test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install --dev
      - name: Run gts
        run: yarn lint
      - name: Build
        run: yarn build
  go:
    name: go test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env: 
      TZ: "Asia/Tokyo"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    - name: Start DB
      run: ./scripts/docker-compose-db.sh up -d
    - name: Build
      run: go build -v ./...
    - name: Test
      run: ./scripts/test.sh -v -coverpkg=./... -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
